server:
  port: 9004

spring:
  application:
    name: hk-article #指定服务名
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.1.6:3306/hk_article?serverTimezone=UTC&useSSL=false
    username: root
    password: 123456
  redis:
    host: 192.168.1.6

eureka:
  client:
    service-url:
      defaultZone: http://localhost:6868/eureka
  instance:
    prefer-ip-address: true

