server:
  port: 9002

spring:
  application:
    name: hk-recruit #指定服务名
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.1.6:3306/hk_recruit?serverTimezone=UTC&useSSL=false
    username: root
    password: 123456

eureka:
  client:
    service-url:
      defaultZone: http://localhost:6868/eureka
  instance:
    prefer-ip-address: true